### ISSUE TITLE
use oauth

### ISSUE THREAD

**Issue by vvo** [SamyPesse/issues#14]
can you use oauth for github logging?

I am not very confident in giving away my login password on a website, plus it's in http.

looks promising !

**Comment by SamyPesse** [comment]
The all website is static, the password is just stored in your browser and use for github api requests.

I don't think it's possible for this application to use oauth, but I can add a message to explain how to create in your GitHub settings a auth token (only for this app).

**Comment by vvo** [comment]
Client side oauth may be feasible, as an example, this popped out on hn: http://adodson.com/hello.js/

You will need to create an empty app for your http://samypesse.github.io/issues/ though.

**Comment by SamyPesse** [comment]
It's impossible to do oauth for GitHub without a server side, and I don't want to use services like oauth.io, etc...

So I added a message to help the user create a token on https://github.com/settings/applications

**Comment by vvo** [comment]
that's fine and works well. thanks

**Comment by geoffrey** [comment]
Basic auth will also not work for people using two factor authentication (without the extra 2FA step), whereas the access token solution always work. Maybe you can add a message to let those users know as well.
